### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Probably easiest to review each commit individually.

**Comment by Ladicek** [comment]
No rush, but could someone please take a look at this? Thank you!

**Comment by gytis** [comment]
Sorry, @Ladicek, I must have missed a notification. Will take care of this today.

**Comment by Ladicek** [comment]
No worries, it would take a few more weeks or perhaps months to become urgent :-)

**Comment by gytis** [comment]
It looks good. Do you mind me squashing the commits or would you prefer them to stay separate?

**Comment by Ladicek** [comment]
I don't really mind. I would expect that keeping the commits separate would be better _for you_, but if you prefer squashing them, I won't oppose.

**Pull request merged**
